sudo: required
dist: xenial

install: true

git:
  depth: 100


stages:
  - name: compile
  - name: test

jobs:
  include:
    # main profile
    - stage: compile
      script: ./test_ci.sh
      name: compile
      arch: arm64
    - stage: compile
      script: ./test_ci.sh
      name: compile
      arch: amd64
    - stage: test
      script: ./test_ci.sh
      name: test
      arch: arm64
    - stage: test
      script: ./test_ci.sh
      name: test
      arch: amd64
